version: '3'
 
services:
  db:
    image: mysql:5.7
    container_name: MES_Database
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: MicroservicesEcommerceSystem_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: MES_Host
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      
    restart: always
    ports:
      - 3101:80
volumes:
  dbdata: